package com.coupons.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * Records a single redemption of a coupon by a concrete user.
 *
 * <p>The unique constraint on {@code (coupon_id, user_id)} is the source of truth for the
 * "one user can redeem a coupon only once" rule. Enforcing it in the database (rather than with a
 * read-then-write check in the service) keeps the guarantee correct under concurrent requests.
 *
 * <p>Accessors and the JPA no-arg constructor are generated by Lombok.
 */
@Entity
@Table(
        name = "coupon_redemption",
        uniqueConstraints = @UniqueConstraint(name = "uq_redemption_user", columnNames = {"coupon_id", "user_id"}),
        indexes = @Index(name = "idx_redemption_coupon", columnList = "coupon_id")
)
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class CouponRedemption {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "coupon_id", nullable = false)
    private UUID couponId;

    @Column(name = "user_id", nullable = false, length = 128)
    private String userId;

    @Column(name = "redeemed_at", nullable = false)
    private Instant redeemedAt;

    public CouponRedemption(UUID couponId, String userId) {
        this.couponId = couponId;
        this.userId = userId;
        this.redeemedAt = Instant.now();
    }
}
