package com.empik.coupons.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Locale;

/**
 * Discount coupon aggregate.
 *
 * <p>The coupon {@code code} is stored in a normalized (upper-case) form so that comparisons are
 * case-insensitive ({@code WIOSNA} and {@code wiosna} are the same coupon). The usage limit is
 * enforced atomically at the database level (see
 * {@link com.empik.coupons.repository.CouponRepository#tryConsume(Long)}); the {@code @Version}
 * column additionally guards any state loaded and mutated through JPA in a concurrent environment.
 *
 * <p>Accessors are generated by Lombok's {@code @Getter}; the protected no-arg constructor required
 * by JPA is generated by {@code @NoArgsConstructor}. {@code @Data} is deliberately avoided on
 * entities because its generated {@code equals}/{@code hashCode}/{@code toString} interact badly with
 * JPA identity and lazy loading.
 */
@Entity
@Table(
        name = "coupon",
        uniqueConstraints = @UniqueConstraint(name = "uq_coupon_code", columnNames = "code")
)
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Coupon {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "code", nullable = false, length = 64, updatable = false)
    private String code;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "max_uses", nullable = false, updatable = false)
    private int maxUses;

    @Column(name = "current_uses", nullable = false)
    private int currentUses;

    @Column(name = "country", nullable = false, length = 2, updatable = false)
    private String country;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    public Coupon(String code, int maxUses, String country) {
        this.code = normalizeCode(code);
        this.country = normalizeCountry(country);
        this.maxUses = maxUses;
        this.currentUses = 0;
        this.createdAt = Instant.now();
    }

    public static String normalizeCode(String code) {
        return code == null ? null : code.trim().toUpperCase(Locale.ROOT);
    }

    public static String normalizeCountry(String country) {
        return country == null ? null : country.trim().toUpperCase(Locale.ROOT);
    }

    public boolean isForCountry(String isoCountryCode) {
        return country.equalsIgnoreCase(normalizeCountry(isoCountryCode));
    }

    public boolean isExhausted() {
        return currentUses >= maxUses;
    }
}
